/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Banegas_Bryan_Prueba_1;

import static Banegas_Bryan_Prueba_1.escoger_oponente.users;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Banegas_Bryan_Prueba_1.crear_cuenta;

/**
 *
 * @author adalb
 */
public class escoger_bando extends javax.swing.JFrame {

    /**
     * Creates new form escoger_bando
     */
    public escoger_bando() {
        ArrayList<Usuario> users = crear_cuenta.listaUsuarios;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    public static String bando="";
    public static String jugador=login.usuarioLogin;
    public static int cantidadHeroes=0;
    public static int cantidadVillanos=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Heroes", "Villanos" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, -1));

        jButton1.setBackground(new java.awt.Color(255, 180, 90));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("ESCOGER");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EscogerBando_Background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        bando=(String) jComboBox2.getSelectedItem();
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(bando.equals("")){
            JOptionPane.showMessageDialog(null, "Tiene que escoger un bando");
        }else{
            if (bando.equals("Heroes")) {
                for (int i = 0; i < users.size(); i++) {
                    if (users.get(i).getnombre().equals(login.usuarioLogin)) {
                        cantidadHeroes = users.get(i).getHeroes();
                        cantidadHeroes++;
                        users.get(i).setHeroes(cantidadHeroes);
                    }
                }
            }else if (bando.equals("Villanos")) {
                for (int i = 0; i < users.size(); i++) {
                    if (users.get(i).getnombre().equals(login.usuarioLogin)) {
                        cantidadVillanos = users.get(i).getVillanos();
                        cantidadVillanos++;
                        users.get(i).setVillanos(cantidadVillanos);
                    }
                }
            }
            if(crear_cuenta.cantidadeusuarios<2){
              partida_nueva pasar=new partida_nueva(users,jugador);
              pasar.setVisible(true);
              this.dispose();
            }else{
                escoger_oponente pasar=new escoger_oponente();
                pasar.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(escoger_bando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(escoger_bando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(escoger_bando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(escoger_bando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new escoger_bando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
