/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Banegas_Bryan_Prueba_1;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author adalb
 */
public class Menu extends javax.swing.JFrame {
    ArrayList<Usuario> users = crear_cuenta.listaUsuarios;
    String nombre;
    
    public Menu(ArrayList<Usuario> ListaUsuarios, String nombre) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.nombre = nombre;
        
    }
    /**
     * Creates new form Menu
     */

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stratego = new javax.swing.JButton();
        configuracion1 = new javax.swing.JButton();
        perfil = new javax.swing.JButton();
        universomarvel = new javax.swing.JButton();
        cerrarsesion = new javax.swing.JButton();
        Background_Menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stratego.setBorder(null);
        stratego.setContentAreaFilled(false);
        stratego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strategoActionPerformed(evt);
            }
        });
        getContentPane().add(stratego, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 250, 90));

        configuracion1.setBorder(null);
        configuracion1.setBorderPainted(false);
        configuracion1.setContentAreaFilled(false);
        configuracion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracion1ActionPerformed(evt);
            }
        });
        getContentPane().add(configuracion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 150, 60));

        perfil.setBorder(null);
        perfil.setContentAreaFilled(false);
        perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilActionPerformed(evt);
            }
        });
        getContentPane().add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 140, 50));

        universomarvel.setBorder(null);
        universomarvel.setBorderPainted(false);
        universomarvel.setContentAreaFilled(false);
        universomarvel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universomarvelActionPerformed(evt);
            }
        });
        getContentPane().add(universomarvel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 140, 50));

        cerrarsesion.setBorder(null);
        cerrarsesion.setContentAreaFilled(false);
        cerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarsesionMouseClicked(evt);
            }
        });
        cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 140, 50));

        Background_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background_MenuPrincipal.png"))); // NOI18N
        getContentPane().add(Background_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void strategoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strategoActionPerformed
        // TODO add your handling code here:
        if(configuracion.clasico==0){
            tutorial1 pasar=new tutorial1();
            pasar.setVisible(true);
            this.dispose();
        }else{
        escoger_bando pasar=new escoger_bando();
        pasar.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_strategoActionPerformed

    private void universomarvelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universomarvelActionPerformed
       UniversoMarvel pasar=new UniversoMarvel(users, nombre);
       pasar.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_universomarvelActionPerformed

    private void configuracion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracion1ActionPerformed
        configuracion pasar=new configuracion();
        pasar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_configuracion1ActionPerformed

    private void perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilActionPerformed
        // TODO add your handling code here:
        Mi_Perfil pasar=new Mi_Perfil(users,nombre,0);
        pasar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_perfilActionPerformed

    private void cerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarsesionMouseClicked
        // TODO add your handling code here:
        configuracion.clasico=0;
        panel_control pasar=new panel_control();
        pasar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarsesionMouseClicked

    private void cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarsesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Background_Menu;
    private javax.swing.JButton cerrarsesion;
    public static javax.swing.JButton configuracion1;
    private javax.swing.JButton perfil;
    private javax.swing.JButton stratego;
    private javax.swing.JButton universomarvel;
    // End of variables declaration//GEN-END:variables
}
