/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Banegas_Bryan_Prueba_1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author adalb
 */
public class panel_control extends javax.swing.JFrame {
    public ArrayList listaUsuarios;
    public ArrayList listaContraseña;

    ArrayList<Usuario> users = crear_cuenta.listaUsuarios;
    ArrayList<Usuario> usersTotal = crear_cuenta.listahistorica;
    ArrayList usuariologs1=partida_nueva.usuariologs1;
    ArrayList usuariologs2=partida_nueva.usuariologs2;
    ArrayList mensajes=partida_nueva.mensajes;
    //Arraylist de logs1
    //Arraylist de logs2
    //Arraylist de mensajes
    
    public panel_control() { 
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        madeinheaven = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 270, 90));

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setMaximumSize(new java.awt.Dimension(238, 73));
        jButton2.setMinimumSize(new java.awt.Dimension(238, 73));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 270, 90));

        madeinheaven.setBackground(new java.awt.Color(255, 0, 0));
        madeinheaven.setForeground(new java.awt.Color(255, 255, 255));
        madeinheaven.setText("X");
        madeinheaven.setBorder(null);
        madeinheaven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madeinheavenActionPerformed(evt);
            }
        });
        getContentPane().add(madeinheaven, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 10, 30, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundMenuInicial.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        crear_cuenta pasar = new crear_cuenta();
        pasar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void madeinheavenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madeinheavenActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < users.size(); i++) {
            this.users.remove(i);
        }
        for (int i = 0; i < users.size(); i++) {
            this.usersTotal.remove(i);
        }
        for (int i = 0; i < usuariologs1.size(); i++) {
            this.usuariologs1.remove(i);
        }
        for (int i = 0; i < usuariologs2.size(); i++) {
            this.usuariologs2.remove(i);
        }
        for (int i = 0; i < mensajes.size(); i++) {
            this.mensajes.remove(i);
        }
        partida_nueva.heroesganado=0;
        partida_nueva.villanosganado=0;
        crear_cuenta.cantidadeusuarios=0;
        JOptionPane.showMessageDialog(null, "Se han borrado todos los datos");
    }//GEN-LAST:event_madeinheavenActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        login pasar = new login();
        pasar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel_control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel_control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel_control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel_control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel_control().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JButton madeinheaven;
    // End of variables declaration//GEN-END:variables

    
}
