/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Banegas_Bryan_Prueba_1;

import java.util.ArrayList;

/**
 *
 * @author adalb
 */
public class UniversoMarvel extends javax.swing.JFrame {

    ArrayList<Usuario> users=crear_cuenta.listaUsuarios;
    ArrayList<Usuario> mensajes=partida_nueva.mensajes;
    String Nombre_G;
    public UniversoMarvel(ArrayList<Usuario> ListaUsuarios, String nombre) {
        
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BatallasBoton = new javax.swing.JButton();
        RankingBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BatallasBoton.setBorder(null);
        BatallasBoton.setContentAreaFilled(false);
        BatallasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatallasBotonActionPerformed(evt);
            }
        });
        getContentPane().add(BatallasBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 210, 90));

        RankingBoton.setBorder(null);
        RankingBoton.setContentAreaFilled(false);
        RankingBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankingBotonActionPerformed(evt);
            }
        });
        getContentPane().add(RankingBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 220, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundUniversoMarvel.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BatallasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatallasBotonActionPerformed
        Batallas pasar=new Batallas(mensajes, Nombre_G);
        pasar.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BatallasBotonActionPerformed

    private void RankingBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankingBotonActionPerformed
        Ranking pasar=new Ranking(users, Nombre_G);
        pasar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RankingBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniversoMarvel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniversoMarvel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniversoMarvel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniversoMarvel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UniversoMarvel(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatallasBoton;
    private javax.swing.JButton RankingBoton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
